<?php

// Plugin definition
$plugin = array(
  'title' => t('Página Principal'),
  'category' => t('Argentina.gob.ar'),
  'icon' => 'pagina-principal-argentina.png',
  'theme' => 'pagina-principal-argentina',
  'admin css' => '../../css/bootstrap_panel.min.css',
  'regions' => array(
    'top' => t('Top'),
    'middle1' => t('Middle1'),
    'middle2' => t('Middle2'),
    'middle3' => t('Middle3'),
    'bottom' => t('Bottom')
  ),
);

