<?php
/**
 * @file
 * Code for the Áreas feature.
 */

include_once 'argentinagobar_areas.features.inc';

function argentinagobar_areas_form_area_node_form_alter(&$form, &$form_state, $form_id){
  $form['options']['status']['#default_value'] = empty($form['nid']['#value']) ? 0 : $form['options']['status']['#default_value'];

  $form['field_sedes']['#access'] = FALSE;
  unset($form['og_group_ref']['und'][0]['default']['#options'][$form['nid']['#value']]);
}
