<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.field_collection_item.field_detalle.field_servicios_relacionados' => '26d7b2d1ce8ba10f33e61f7708ef05524745b952',
  'field.field_collection_item.field_medida.field_cantidades' => 'ba198727dc651acf74e45c2482ce5afbdcbfae07',
  'field_group.group_acciones|node|tramite|form' => '606567c8ba14b607eedca0dea5d3009aeb9c02e0',
  'field_group.group_configuracion|node|tramite|form' => '809052cb67d1f9ab5f9f74108de1baff00c0e0aa',
  'field_group.group_informacion_adicional|node|tramite|form' => 'e34d85834cde261b57be224a683e080efbd706e3',
  'field_group.group_titulo_descripcion|node|tramite|form' => 'f56b75c71778c834a96dda6f379e639f5dae167a',
  'field_group.group_tramites_relacionados|node|tramite|form' => 'ba4eb82ce0ff213045cf28ee99775699731b78e8',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'text',
  'list',
  'options',
  'ctools',
  'field_group',
);
