<?php

function argentinagobar_og_menu() {

  $items['admin/content/group'] = array(
    'title' => t('Contenido del Área'),
    'description' => 'Lista el contenido del área a la que pertenece el usuario.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('argentinagobar_og_node_admin_content'),
    'access arguments' => array('access content group'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    //'file' => 'argentinagobar_og.admin.inc',
  );
  return $items;
}

function argentinagobar_og_node_admin_content($form, &$form_state){

  // Build the sortable table header.
  $header = array(
    'title' => array('data' => t('Title'), 'field' => 'n.title'),
    'type' => array('data' => t('Type'), 'field' => 'n.type'),
    'author' => t('Author'),
    'status' => array('data' => t('Status'), 'field' => 'n.status'),
    'changed' => array('data' => t('Updated'), 'field' => 'n.changed', 'sort' => 'desc')
  );

  $header['operations'] = array('data' => t('Operations'));

  foreach (obtenerNodos() as $item) {
    $node = node_load($item->nid);
    $options[$node->nid] = array(
      'title' => array(
        'data' => array(
          '#type' => 'link',
          '#title' => $node->title,
          '#href' => 'node/' . $node->nid,
          '#suffix' => ' ' . theme('mark', array('type' => node_mark($node->nid, $node->changed))),
        ),
      ),
      'type' => check_plain(node_type_get_name($node)),
      'author' => theme('username', array('account' => $node)),
      'status' => $node->status ? t('published') : t('not published'),
      'changed' => format_date($node->changed, 'short'),
    );
    // Build a list of all the accessible operations for the current node.
    $operations = array();
    if (node_access('update', $node)) {
      $operations['edit'] = array(
        'title' => t('edit'),
        'href' => 'node/' . $node->nid . '/edit',
        'query' => $destination,
      );
    }
    if (node_access('delete', $node)) {
      $operations['delete'] = array(
        'title' => t('delete'),
        'href' => 'node/' . $node->nid . '/delete',
        'query' => $destination,
      );
    }
    $options[$node->nid]['operations'] = array();
    if (count($operations) > 1) {
      // Render an unordered list of operations links.
      $options[$node->nid]['operations'] = array(
        'data' => array(
          '#theme' => 'links__node_operations',
          '#links' => $operations,
          '#attributes' => array('class' => array('links', 'inline')),
        ),
      );
    }
    elseif (!empty($operations)) {
      // Render the first and only operation as a link.
      $link = reset($operations);
      $options[$node->nid]['operations'] = array(
        'data' => array(
          '#type' => 'link',
          '#title' => $link['title'],
          '#href' => $link['href'],
          '#options' => array('query' => $link['query']),
        ),
      );
    }
  }


  // Only use a tableselect when the current user is able to perform any
  // operations.
  if ($admin_access) {
    $form['nodes'] = array(
      '#type' => 'tableselect',
      '#header' => $header,
      '#options' => $options,
      '#empty' => t('No content available.'),
    );
  }
  // Otherwise, use a simple table.
  else {
    $form['nodes'] = array(
      '#theme' => 'table',
      '#header' => $header,
      '#rows' => $options,
      '#empty' => t('No content available.'),
    );
  }

  $form['pager'] = array('#markup' => theme('pager'));

  return $form;
}

function obtenerNodos(){
  foreach (og_get_groups_by_user($account = NULL, $group_type = NULL)['node'] as $key => $value) {
    $grupos[] = $value;
  }

  $view = views_get_view('og_all_user_group_content');
  $view->set_arguments(
    array(
      !empty($grupos) ? implode('+', $grupos) : 'all'
    )
  );
  //$view->set_items_per_page($conf["cantidad_links"]);
  $view->execute();
  return $view->result;
}

function argentinagobar_og_permission() {
  return array(
    'access content group' => array(
      'title' => t('Acceder a la página de resumen de contenido del grupo'),
      'description' => t('Obtener el listado del contenido del grupo.'),
    ),
  );
}