<?php
/**
 * @file
 * Code for the argentinagobar_libros feature.
 */

include_once 'argentinagobar_libros.features.inc';

function argentinagobar_libros_form_book_node_form_alter(&$form, &$form_state, $form_id){

  drupal_add_js(drupal_get_path('module', 'argentinagobar_libros') . '/js/div.js');

  $form['book']['weight']['#title'] = t('Indexado');
  $form['book']['weight']['#description'] = t('Si más de un item tienen el mismo índice los ordena alfabéticamente');
}

// no me pisen
function argentinagobar_libros_module_implements_alter(&$implementations, $hook){
  if ($hook == 'form_alter' && array_key_exists('argentinagobar_libros', $implementations)){
    // Move my_module_rdf_mapping() to the end of the list. module_implements()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['argentinagobar_libros'];
    unset($implementations['argentinagobar_libros']);
    $implementations['argentinagobar_libros'] = $group;
  }
}

function obtenerNodeViewTabIndex($tabs){

  $nodeViewTabIndex = FALSE;

  foreach ($tabs as $key => $tab) {
    if($tab['#link']['path'] == 'node/%/view'){
      $nodeViewTabIndex = $tab['#link']['path'] == 'node/%/view' ? $key : $nodeViewTabIndex;
    }
  }

  return $nodeViewTabIndex;
}

function actualizarNodeViewTab(&$data, $tabs, $index){

  $link_path = explode("/", $tabs[$index]['#link']['href']);
  $tokenContentAccess = false;

  if(count($link_path) > 1){
    $node = node_load($link_path[1]);
    $tokenContentAccess = obtenerTCA($node);
  }

  if($tokenContentAccess){
    $data['tabs'][0]['output'][$index]['#link']['localized_options']['query'] = array('tca' => $tokenContentAccess);
  }
}

function argentinagobar_libros_menu_local_tasks_alter(&$data, $router_item, $root_path){

  $targetTab = FALSE;

  if(array_key_exists('tabs', $data)) {
    if(!empty($data['tabs'][0]['output'])){
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        if($tab['#link']['path'] == 'node/%/views'){
          $targetTabKey = $key;
          $targetTab = $tab['#link']['path'] == 'node/%/view' ? $tab : $targetTab;
        }
      }

      $nodeViewTabIndex = obtenerNodeViewTabIndex($data['tabs'][0]['output']);

      if(!$nodeViewTabIndex) {
        actualizarNodeViewTab($data, $data['tabs'][0]['output'], $nodeViewTabIndex);
      }
    }
  }
}

/**
 * Implements hook_menu_alter
 */
function argentinagobar_libros_menu_alter(&$items) {
  $items['node/%node']['title callback'] = 'argentinagobar_libros_page_title';
}

/**
 * Helper function to replace node_page_title
 */
function argentinagobar_libros_page_title($node) {
  if (!$node) {
    return '';
  }

  if (is_numeric($node)) {
    $node = node_load($node);
  }
  return !empty($node->title) ? $node->title : '';
}
